data_param:
  batch_size: 4 # batch size
  data_root: ../FHN/data/polyvore # data root
  image_root: ../FHN/data/polyvore # data root
  data_set: tuples_519 # data set
  len_his: 10 # size of user his behaviour
  nega_mode: RandomOnline # negative outfits strategy
  num_workers: 2 # number of workers
  use_lmdb: true # use lmbd data
  use_semantic: false # use sentance data
  use_visual: true # use visual data

train_data_param:
  shuffle: true # do shuffle
  data_mode: PairWise # output data format
  phase: train # split

test_data_param:
  shuffle: false # do not shuffle
  data_mode: PairWise # output data format
  phase: val # split

net_param:
  name: FashionNet
  num_users: 519 # number of users
  dim: 128 # dimension of binary codes
  backbone: alexnet # backbone for feature extractor
  hash_types: 3 # type of hash codes
  scale_tanh: false # use scale tahn
  use_semantic: false # use semantic features
  without_binary: true # use binary module
  use_visual: true # user visdual features
  margin: 0.1 # margin for vse-loss, if exists
  num_seeds: 4 # num of factorization, if use

solver_param:
  name: "FashionNetSolver"
  display: 20 # display interval
  epochs: 150 # total epoches
  gamma: 1.0 # gamma for scale-tanh
  gpus: [3]
  visdom_env: fashion_hash_net
  visdom_title: FIN519_his20
  checkpoints: ./checkpoints/FIN519_his20
  optim_param:
    name: SGD
    lr: [5, 0.001, 0.005, 0.01]
    # lr: [5, 0.01, 0.01, 0.001, 0.005, 0.01] # learning rate for each group, if use factorization
    weight_decay: 1.0e-06
    grad_param: { momentum: 0.9 } # setting for SGD
    lr_scheduler: ReduceLROnPlateau
    scheduler_param:
      { cooldown: 10, factor: 0.5, patience: 10, threshold: 0.05 }

#resume: checkpoints/FIN519_his_latest.solver
log_file: logs/train/FIN519_his20.log
log_level: DEBUG
