data_param:
  batch_size: 128 # batch size
  data_root: ../FHN/data/polyvore # data root
  image_root: ../FHN/data/polyvore # image root
  data_set: tuples_630 # data set
  nega_mode: RandomOnline # negative outfits strategy
  num_workers: 4 # number of workers
  use_lmdb: true # use lmbd data
  use_semantic: false # use sentance data
  use_visual: true # use visual data

train_data_param:
  shuffle: true # do shuffle
  data_mode: PairWise # output data format
  phase: train # split

test_data_param:
  shuffle: false # do not shuffle
  data_mode: PairWise # output data format
  phase: val # split

net_param:
  #batch_size: 90
  #gpus: [1,2,3]
  name: FashionNet
  num_users: 630 # number of users
  dim: 128 # dimension of binary codes
  backbone: alexnet # backbone for feature extractor
  hash_types: 3 # type of hash codes
  scale_tanh: false # use scale tahn
  without_binary: true
  use_semantic: false # use semantic features
  use_visual: true # user visdual features
  margin: 0.1 # margin for vse-loss, if exists

solver_param:
  name: "FashionNetSolver"
  display: 20 # display interval
  epochs: 100 # total epoches
  gamma: 1.0 # gamma for scale-tanh
  gpus: [0]
  visdom_env: fashion_hash_net
  visdom_title: fin_uof_match3
  checkpoints: ./checkpoints/fin_uof_match3
  optim_param:
    name: SGD
    # lr: [5, 0.001, 0.005, 0.005, 0.01] # learning rate for each group
    # lr: [10, 10, 0.001, 0.01, 0.01, 0.1]
    lr: [10, 0.01, 0.01, 0.001, 0.01, 0.1]
    weight_decay: 1.0e-06
    grad_param: { momentum: 0.9 } # setting for SGD
    lr_scheduler: ReduceLROnPlateau
    scheduler_param:
      { cooldown: 10, factor: 0.5, patience: 10, threshold: 0.05 }

#load_trained: checkpoints/fashion_hash_net_vse_t3_u630_latest.pth
#resume: checkpoints/fin_his_reg3_latest.solver
log_file: logs/train/fin_uof_match3.log
log_level: DEBUG
